/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/brand.ts
 * Command: astryx theme build src/themes/brand.ts --out src/themes/brand.theme.css
 * Generated: 2026-08-06T16:22:48.051Z
 */

/// <reference path="./brand-guide.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const brandGuideTheme: DefinedTheme;
