/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/brand.ts
 * Command: astryx theme build src/themes/brand.ts --out src/themes/brand.theme.css
 * Generated: 2026-07-30T21:24:18.925Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
