import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by `astryx theme build`
      "src/themes/brand-guide.js",
      "src/themes/brand-guide.d.ts",
      "src/themes/brand-guide.variants.d.ts",
      "src/themes/brand.generated.ts",
      "src/themes/brand.theme.css",
    ],
  },
];

export default eslintConfig;
